// Package worldmap renders an ASCII-art world map for the TerminalTAK TUI.
//
// Land masses are sourced from Natural Earth's ne_110m_land dataset
// (public domain) embedded via go:embed and rendered with Unicode Braille
// pattern characters for sub-pixel resolution. The projection is plain
// equirectangular plus an AspectFit step that compensates for the
// terminal cell aspect ratio (~1×2) and the cos(lat) shortening of
// longitude distance at high latitudes — without it, viewports near the
// poles render as flattened horizontal pancakes.
package worldmap

import (
	"math"
	"strings"
)

// CellAspect is the typical terminal cell width-to-height pixel ratio.
// Most monospace fonts paint cells about twice as tall as they are wide,
// so 0.5 is a reasonable approximation. AspectFit uses this to widen a
// viewport so a square geographic area renders as a visually square
// region on screen.
const CellAspect = 0.5

// LatLon is a single geographic coordinate.
type LatLon struct {
	Lat, Lon float64
}

// Viewport defines which slice of the world is rendered into the canvas.
// MinLat must be <= MaxLat and MinLon <= MaxLon (we do not handle
// dateline-crossing viewports in v1).
type Viewport struct {
	MinLat, MaxLat float64
	MinLon, MaxLon float64
}

// World is the full-globe viewport.
var World = Viewport{MinLat: -90, MaxLat: 90, MinLon: -180, MaxLon: 180}

// SwedenBBox is the geographic bounding box for Sweden — used by the TUI
// as a minimum-zoom guarantee when the user's own position is inside it,
// so the live map always shows their entire country in context.
var SwedenBBox = Viewport{MinLat: 55.0, MaxLat: 69.1, MinLon: 10.5, MaxLon: 24.5}

// Contains reports whether (lat, lon) is inside v.
func (v Viewport) Contains(lat, lon float64) bool {
	return lat >= v.MinLat && lat <= v.MaxLat && lon >= v.MinLon && lon <= v.MaxLon
}

// Expand returns a viewport whose bounds are the union of v and other —
// i.e. v widened (never shrunk) to include every point of other.
func (v Viewport) Expand(other Viewport) Viewport {
	if other.MinLat < v.MinLat {
		v.MinLat = other.MinLat
	}
	if other.MaxLat > v.MaxLat {
		v.MaxLat = other.MaxLat
	}
	if other.MinLon < v.MinLon {
		v.MinLon = other.MinLon
	}
	if other.MaxLon > v.MaxLon {
		v.MaxLon = other.MaxLon
	}
	return v
}

// Project returns the (col, row) cell into a width×height canvas where the
// given lat/lon lands. The canvas is row-major with row 0 at the top
// (north). Cells are clamped to the canvas bounds.
func (v Viewport) Project(lat, lon float64, width, height int) (col, row int) {
	if width <= 0 || height <= 0 {
		return 0, 0
	}
	lonRange := v.MaxLon - v.MinLon
	latRange := v.MaxLat - v.MinLat
	if lonRange <= 0 {
		lonRange = 1
	}
	if latRange <= 0 {
		latRange = 1
	}
	col = int((lon - v.MinLon) / lonRange * float64(width))
	row = int((v.MaxLat - lat) / latRange * float64(height))
	if col < 0 {
		col = 0
	}
	if col >= width {
		col = width - 1
	}
	if row < 0 {
		row = 0
	}
	if row >= height {
		row = height - 1
	}
	return col, row
}

// Marker is one rendered point on the map.
type Marker struct {
	Lat, Lon float64
	Rune     rune
}

// Render paints viewport into a width×height ASCII canvas, draws every
// marker on top in order (later markers overwrite earlier), and returns the
// canvas as a string with newline-separated rows. Out-of-viewport markers
// are silently dropped.
//
// The basemap is generated by Basemap; callers can substitute their own by
// pre-allocating a [][]rune and using Compose. Render is the typical entry
// point for the TUI.
func Render(viewport Viewport, width, height int, markers []Marker) string {
	canvas := Basemap(viewport, width, height)
	Compose(canvas, viewport, markers)
	return canvasToString(canvas)
}

// Compose draws markers onto an existing canvas in place.
func Compose(canvas [][]rune, viewport Viewport, markers []Marker) {
	height := len(canvas)
	if height == 0 {
		return
	}
	width := len(canvas[0])
	for _, m := range markers {
		if m.Lat < viewport.MinLat || m.Lat > viewport.MaxLat {
			continue
		}
		if m.Lon < viewport.MinLon || m.Lon > viewport.MaxLon {
			continue
		}
		col, row := viewport.Project(m.Lat, m.Lon, width, height)
		canvas[row][col] = m.Rune
	}
}

// AspectFit returns a copy of v whose lat/lon span ratio matches the
// canvas pixel aspect at the viewport's centre latitude. It expands one
// axis of the viewport (never shrinks) so the rendered map keeps the
// caller's content fully in frame — the user just sees more ocean on the
// stretched side.
//
// The math:
//
//   - canvasPixelAspect = width / (height * 1/CellAspect)
//     (height in cells × cells-per-pixel-tall = pixel height; same for width)
//   - geoAspect         = lonSpan * cos(centerLat) / latSpan
//     (longitude distance shrinks by cos(lat) — that is the whole reason
//     equirectangular looks wrong at high latitudes)
//
// If geoAspect < canvasPixelAspect the map is too tall for the canvas
// → widen the lon-span. Otherwise the map is too wide → widen lat-span.
// The result is clamped to [-90,90] / [-180,180].
func (v Viewport) AspectFit(width, height int) Viewport {
	if width <= 0 || height <= 0 {
		return v
	}
	latSpan := v.MaxLat - v.MinLat
	lonSpan := v.MaxLon - v.MinLon
	if latSpan <= 0 || lonSpan <= 0 {
		return v
	}
	centerLat := (v.MinLat + v.MaxLat) / 2
	cosLat := math.Cos(centerLat * math.Pi / 180)
	if cosLat < 0.05 {
		cosLat = 0.05 // avoid blowing up near the poles
	}
	canvasAspect := float64(width) * CellAspect / float64(height)
	geoAspect := lonSpan * cosLat / latSpan

	if geoAspect < canvasAspect {
		// Need more longitude — widen the lon-span symmetrically.
		targetLon := latSpan * canvasAspect / cosLat
		mid := (v.MinLon + v.MaxLon) / 2
		v.MinLon = mid - targetLon/2
		v.MaxLon = mid + targetLon/2
	} else {
		// Need more latitude — widen the lat-span symmetrically.
		targetLat := lonSpan * cosLat / canvasAspect
		mid := (v.MinLat + v.MaxLat) / 2
		v.MinLat = mid - targetLat/2
		v.MaxLat = mid + targetLat/2
	}
	if v.MinLat < -90 {
		v.MinLat = -90
	}
	if v.MaxLat > 90 {
		v.MaxLat = 90
	}
	if v.MinLon < -180 {
		v.MinLon = -180
	}
	if v.MaxLon > 180 {
		v.MaxLon = 180
	}
	return v
}

// AutoFit returns a viewport that snugly contains every coord plus a 10%
// margin on each side. If coords is empty, World is returned. If the bbox
// degenerates (single point or zero area), the viewport widens to a fixed
// 30°×30° window centred on the point so we never divide by zero.
//
// AutoFit does NOT compensate for canvas aspect — that is AspectFit's job.
// Callers that have a render target should compose them: AutoFit(coords)
// then AspectFit(width, height).
func AutoFit(coords []LatLon) Viewport {
	if len(coords) == 0 {
		return World
	}
	minLat, maxLat := coords[0].Lat, coords[0].Lat
	minLon, maxLon := coords[0].Lon, coords[0].Lon
	for _, c := range coords[1:] {
		if c.Lat < minLat {
			minLat = c.Lat
		}
		if c.Lat > maxLat {
			maxLat = c.Lat
		}
		if c.Lon < minLon {
			minLon = c.Lon
		}
		if c.Lon > maxLon {
			maxLon = c.Lon
		}
	}
	latSpan := maxLat - minLat
	lonSpan := maxLon - minLon
	// degenerateSpan: if the bbox collapses to (effectively) a point we
	// widen to a usable map window. For larger spans we just add a 10%
	// margin so the user sees a comfortable amount of map context.
	const degenerateSpan = 2.0
	const widenedSpan = 30.0
	if latSpan < degenerateSpan {
		mid := (minLat + maxLat) / 2
		minLat, maxLat = mid-widenedSpan/2, mid+widenedSpan/2
	} else {
		pad := latSpan * 0.1
		minLat -= pad
		maxLat += pad
	}
	if lonSpan < degenerateSpan {
		mid := (minLon + maxLon) / 2
		minLon, maxLon = mid-widenedSpan/2, mid+widenedSpan/2
	} else {
		pad := lonSpan * 0.1
		minLon -= pad
		maxLon += pad
	}
	if minLat < -90 {
		minLat = -90
	}
	if maxLat > 90 {
		maxLat = 90
	}
	if minLon < -180 {
		minLon = -180
	}
	if maxLon > 180 {
		maxLon = 180
	}
	return Viewport{MinLat: minLat, MaxLat: maxLat, MinLon: minLon, MaxLon: maxLon}
}

func canvasToString(canvas [][]rune) string {
	var b strings.Builder
	for i, row := range canvas {
		if i > 0 {
			b.WriteByte('\n')
		}
		b.WriteString(string(row))
	}
	return b.String()
}
